export const LOGOS = {
  glean: 'https://app.glean.com/images/glean-logo2.svg',
  gleanText: 'https://app.glean.com/images/glean-text3.svg',
  salesforce: 'https://app.glean.com/images/logos/salesforce.svg',
  jira: 'https://app.glean.com/images/logos/jira3.svg',
  confluence: 'https://app.glean.com/images/logos/confluence3.svg',
  gdrive: 'https://app.glean.com/images/logos/gdrive3.svg',
  gmail: 'https://app.glean.com/images/logos/gmail3.svg',
  teams: 'https://app.glean.com/images/logos/teams.svg',
  sharepoint: 'https://app.glean.com/images/logos/sharepoint.svg',
  servicenow: 'https://app.glean.com/images/logos/servicenow.svg',
  outlook: 'https://app.glean.com/images/logos/outlook.svg',
  gong: 'https://app.glean.com/images/logos/gong.svg',
  tableau: 'https://app.glean.com/images/logos/tableau.svg',
  openai: 'https://app.glean.com/images/logos/openai.svg',
  gemini: 'https://app.glean.com/images/logos/google-gemini.svg',
  claude: 'https://app.glean.com/images/claude.svg',

  jiraEpic: 'https://app.glean.com/images/jira/epic.svg',
  docx: 'https://app.glean.com/images/mimeTypes/docx-fabric.svg',
  pptx: 'https://app.glean.com/images/mimeTypes/pptx-fabric.svg',
  xlsx: 'https://app.glean.com/images/mimeTypes/xlsx-fabric.svg',

  search: 'https://app.glean.com/images/feather/search.svg',
  database: 'https://app.glean.com/images/feather/database.svg',
  lock: 'https://app.glean.com/images/feather/lock.svg',
  user: 'https://app.glean.com/images/feather/user.svg',
  users: 'https://app.glean.com/images/users-2.svg',
  globe: 'https://app.glean.com/images/feather/globe.svg',
  zap: 'https://app.glean.com/images/zap-filled.svg',
  lightbulb: 'https://app.glean.com/images/lightbulb-3.svg',
  layers: 'https://app.glean.com/images/layers-2.svg',
  agent: 'https://app.glean.com/images/agent-3.svg',
  sparkles: 'https://app.glean.com/images/message-with-sparkles-3.svg',
  clock: 'https://app.glean.com/images/feather/clock.svg',
  star: 'https://app.glean.com/images/feather/star.svg',
  settings: 'https://app.glean.com/images/feather/settings.svg',
} as const;
